// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UnitTests.Features.Products
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RecuperarProdutosFeature : object, Xunit.IClassFixture<RecuperarProdutosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetAllProducts.feature"
#line hidden
        
        public RecuperarProdutosFeature(RecuperarProdutosFeature.FixtureData fixtureData, UnitTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Products", "Recuperar produtos", "  Como consumidor de API\r\n  Quero recuperar todos os produtos\r\n  Para que eu poss" +
                    "a visualizar a lista de produtos dispon�veis", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recuperar todos os produtos com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Recuperar produtos")]
        [Xunit.TraitAttribute("Description", "Recuperar todos os produtos com sucesso")]
        public void RecuperarTodosOsProdutosComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recuperar todos os produtos com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CategoryId",
                            "Name",
                            "Description",
                            "Price",
                            "Image"});
                table3.AddRow(new string[] {
                            "1",
                            "10",
                            "Produto1",
                            "Descricao do produto 1",
                            "100.50",
                            "image1.jpg"});
                table3.AddRow(new string[] {
                            "2",
                            "20",
                            "Produto2",
                            "Descricao do produto 2",
                            "200.75",
                            "image2.jpg"});
#line 7
    testRunner.Given("que a API tem os seguintes produtos", ((string)(null)), table3, "Given ");
#line hidden
#line 11
    testRunner.When("solicito todos os produtos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
    testRunner.Then("a resposta deve conter 2 produtos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
    testRunner.And("a resposta deve incluir um produto com o nome \"Produto1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recuperar produtos por lista de IDs")]
        [Xunit.TraitAttribute("FeatureTitle", "Recuperar produtos")]
        [Xunit.TraitAttribute("Description", "Recuperar produtos por lista de IDs")]
        public void RecuperarProdutosPorListaDeIDs()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recuperar produtos por lista de IDs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CategoryId",
                            "Name",
                            "Description",
                            "Price",
                            "Image"});
                table4.AddRow(new string[] {
                            "1",
                            "10",
                            "Produto1",
                            "Descricao do produto 1",
                            "100.50",
                            "image1.jpg"});
                table4.AddRow(new string[] {
                            "2",
                            "20",
                            "Produto2",
                            "Descricao do produto 2",
                            "200.75",
                            "image2.jpg"});
#line 16
    testRunner.Given("que a API tem os seguintes produtos", ((string)(null)), table4, "Given ");
#line hidden
#line 20
    testRunner.When("solicito produtos com os IDs \"1,2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    testRunner.Then("a resposta deve conter 2 produtos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
    testRunner.And("a resposta deve incluir um produto com o nome \"Produto2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RecuperarProdutosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RecuperarProdutosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
