apiVersion: v1
kind: Service
metadata:
  name: wa-productstoolsapi-service
spec:
  selector:
    app: wa-productstoolsapi
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer