apiVersion: v1
kind: Pod
metadata:
  name: wa-productstoolsapi
  labels:
    app: wa-productstoolsapi
spec:
  containers:
    - name: wa-productstoolsapi-container
      image: willmarques/wa-fastfoodselfservice.products_tools_api:latest
      ports:
        - containerPort: 5001
      envFrom:
        - configMapRef:
            name: wa-productstoolsapi-configmap